import 'dotenv/config';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';
import pg from 'pg';

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter } as never);

const REVIEWERS = [
  { phone: '+923111001001', name: 'Usman Tariq' },
  { phone: '+923111001002', name: 'Hira Noor' },
  { phone: '+923111001003', name: 'Bilal Chaudhry' },
  { phone: '+923111001004', name: 'Sana Riaz' },
  { phone: '+923111001005', name: 'Faisal Mehmood' },
  { phone: '+923111001006', name: 'Mehwish Saleem' },
  { phone: '+923111001007', name: 'Zubair Ahmed' },
  { phone: '+923111001008', name: 'Ayesha Malik' },
];

// Pool of realistic review texts
const REVIEW_POOL: { rating: number; comment: string }[] = [
  { rating: 5, comment: 'Absolutely brilliant. The landlord was very cooperative, handover was smooth, and all utilities were working from day one. Would highly recommend this property to anyone looking in this area.' },
  { rating: 5, comment: 'Very clean and well-maintained. Water pressure is great, electricity connections are solid. Landlord responded to every query within hours. Renewed lease for second year.' },
  { rating: 5, comment: 'Best rental experience I have had in years. No hidden charges, lease was transparent, and the inspection report on this platform saved me from a bad previous experience elsewhere.' },
  { rating: 4, comment: 'Good property overall. Location is very convenient and the rooms are spacious. Minor issue with the kitchen tap on move-in but landlord had it fixed within two days. Happy here.' },
  { rating: 4, comment: 'Comfortable and affordable for the area. Parking space is a bonus. Neighbours are decent. The platform made the whole process paperless which I appreciated.' },
  { rating: 4, comment: 'Solid place to live. The online lease process through Rent Kar Ghar was smooth — much better than dealing with physical papers. A few scuffs on the walls but nothing serious.' },
  { rating: 4, comment: 'Was initially worried about renting without physically meeting the landlord first, but the NADRA-verified badge gave me confidence. Moved in and everything was as described.' },
  { rating: 3, comment: 'Decent property but the neighbourhood can be noisy during evenings. The landlord is helpful enough. The digital lease feature is a great idea — saved a lot of back and forth.' },
  { rating: 5, comment: 'Masha Allah very nice house. Bhai sahab (landlord) is very understanding and does not bother unnecessarily. Geyser and geysers all work well. Pani pressure bhi theek hai.' },
  { rating: 4, comment: 'We have been living here for 8 months now. Children are happy, school is close by. Gas and electricity connections are fine. Landlord takes care of maintenance promptly.' },
  { rating: 5, comment: 'The inspection certificate shown on the listing was the deciding factor for us. Moved in with full confidence. House was exactly as shown in the photos — no surprises.' },
  { rating: 4, comment: 'Very pleasant experience using this platform. The inspection team was professional and the full report was detailed. Property lives up to its listing description.' },
  { rating: 3, comment: 'Apartment is fine, slightly overpriced for the size but the location justifies it. Lift maintenance could be better. Landlord is generally responsive. Overall okay.' },
  { rating: 5, comment: 'Exceptional. Shifted from Lahore and was nervous about finding a place remotely. The verification system and detailed photos made it easy to trust the listing. Zero regrets.' },
  { rating: 4, comment: 'Clean, airy, and the rent is fair for this locality. The lease agreement PDF generated by the platform is professional and signed digitally. Very modern system.' },
];

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function shuffled<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

async function main() {
  console.log('Upserting reviewer accounts…');
  const reviewers = await Promise.all(
    REVIEWERS.map(r =>
      prisma.user.upsert({
        where: { phone: r.phone },
        create: { phone: r.phone, name: r.name, role: 'TENANT', verificationTier: 'BASIC', isActive: true, acceptedTerms: true },
        update: { name: r.name },
        select: { id: true, name: true },
      })
    )
  );
  console.log(`  ${reviewers.length} reviewer accounts ready`);

  const listings = await prisma.listing.findMany({ select: { id: true, title: true }, where: { status: 'ACTIVE' } });
  console.log(`Seeding reviews for ${listings.length} active listings…`);

  let total = 0;
  for (const listing of listings) {
    // 2–4 reviews per listing, from a random subset of reviewers
    const count = 2 + Math.floor(Math.random() * 3);
    const chosenReviewers = shuffled(reviewers).slice(0, count);

    for (const reviewer of chosenReviewers) {
      const { rating, comment } = pick(REVIEW_POOL);
      try {
        await prisma.review.upsert({
          where: { listingId_authorId: { listingId: listing.id, authorId: reviewer.id } },
          create: { listingId: listing.id, authorId: reviewer.id, rating, comment },
          update: {},
        });
        total++;
      } catch {
        // skip conflicts
      }
    }

    const avg = (await prisma.review.aggregate({ where: { listingId: listing.id }, _avg: { rating: true } }))._avg.rating?.toFixed(1);
    console.log(`  ✓ ${listing.title.slice(0, 40).padEnd(40)} ${count} reviews · avg ${avg}`);
  }

  console.log(`\nDone — ${total} reviews seeded across ${listings.length} listings.`);
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => { pool.end(); });
